=== dafik-li/car_service/src/main/resources/new_xml/new_detail.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:complexType name="CostType"/>

    <xs:complexType name="CostsType">
        <xs:sequence>
            <xs:element name="cost" type="CostType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="DetailsType">
        <xs:sequence>
            <xs:element name="detail" type="DetailType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="ServiceType"/>

    <xs:complexType name="ServicesType">
        <xs:sequence>
            <xs:element name="service" type="ServiceType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="CarType">
        <xs:all>
            <xs:element name="brand" type="xs:string"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="year" type="xs:int"/>
            <xs:element name="services" type="ServicesType"/>
            <xs:element name="details" type="DetailsType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>


    <xs:complexType name="DetailType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="price" type="xs:int"/>
            <xs:element name="carId" type="CarType"/>
            <xs:element name="inStock" type="xs:boolean"/>
            <xs:element name="deliveryDays" type="xs:int"/>
            <xs:element name="costs" type="CostsType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    
    <xs:element name="detail" type="DetailType"/>


</xs:schema>

=== dafik-li/car_service/src/main/resources/new_xml/new_detail.xml
<?xml version="1.0" encoding="UTF-8"?>
<detail id="10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="new_detail.xsd">
    <name>new detail</name>
    <price>100</price>
    <carId id="8">
        <brand>audi</brand>
        <model>a4</model>
        <year>2024</year>
        <services> </services>
        <details> </details>
    </carId>
    <inStock>1</inStock>
    <deliveryDays>0</deliveryDays>
    <costs> </costs>
</detail>
