=== dafik-li/car_service/src/main/resources/new_xml/new_employee.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="ServiceType"/>

    <xs:complexType name="ServicesType">
        <xs:sequence>
            <xs:element name="service" type="ServiceType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CompanyType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="DepartmentType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="companyId" type="CompanyType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="level" type="xs:integer"/>
            <xs:element name="salary" type="xs:integer"/>
            <xs:element name="phoneNumber" type="xs:string"/>
            <xs:element name="departmentId" type="DepartmentType"/>
            <xs:element name="services" type="ServicesType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:element name="employee" type="EmployeeType"/>

</xs:schema>

=== dafik-li/car_service/src/main/resources/new_xml/new_employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee id="10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="new_employee.xsd">
    <name>Arnold</name>
    <surname>Schwarzenegger</surname>
    <age>76</age>
    <position>CEO</position>
    <level>10</level>
    <salary>100000</salary>
    <phoneNumber>375299000000</phoneNumber>
    <departmentId id="7">
        <name>Director</name>
        <companyId id="7">
            <name>Tony Montana Service - Minsk</name>
            <address>Minsk, av. F. Skaryny, 8</address>
        </companyId>
    </departmentId>
    <services> </services>
</employee>
